name: Build Raspberry Pi Image

on:
  push:
    branches:
      - arm64
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: setraspiconfig
        uses: usimd/pi-gen-action@v1
        id: pi-gen-build
        with:
          apt-proxy: ''
          compression: xz
          compression-level: 8
          disable-first-boot-user-rename: 0
          pi-gen-repository: rishimathur14/RasQberry-pi-gen
          pi-gen-version: arm64
          docker-opts: ''
          enable-noobs: false
          enable-ssh: 0
          export-last-stage-only: true
          extra-host-dependencies: ''
          extra-host-modules: ''
          github-token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          hostname: raspberrypi
          image-name: 'rasqberry-two'
          increase-runner-disk-size: true
          keyboard-keymap: gb
          keyboard-layout: English (UK)
          locale: en_GB.UTF-8
          password: 'Qiskit1!'
          pi-gen-release: Raspberry Pi Qiskit Release
          pubkey-only-ssh: 0
          stage-list: stage0 stage1 stage2 stage3 stage4 stage5
          timezone: Europe/London
          verbose-output: false

      - uses: actions/upload-artifact@v4
        name: upload_pi_gen_image
        with:
          name: pi-gen-image
          path: ${{ steps.pi-gen-build.outputs.image-path }}

      - name: Commit and Push Image to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: |
          # Verify the path and list files for debugging
          echo  "worskspace :"$GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git checkout arm64
          echo "Image path: ${{ steps.pi-gen-build.outputs.image-path }}"
          ls -lrt ${{ steps.pi-gen-build.outputs.image-path }}

          # Create a deploy folder if it doesn't exist
          mkdir -p deploy

          # Copy the image to the deploy folder
          cp ${{ steps.pi-gen-build.outputs.image-path }} deploy/

          # Add, commit, and push the image
          git add deploy/*
          git commit -m "Add new Raspberry Pi image"
          git push
