name: Build Raspberry Pi Image

on:
  push:
    branches:
      - arm64
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

      - name: Install Pi-gen (Raspberry Pi OS image generator)
        run: |
          git clone https://github.com/rishimathur14/RasQberry-pi-gen.git -b arm64
          cd RasQberry-pi-gen

      - name: Configure Pi-gen Build
        run: |
          chmod -R 755 RasQberry-pi-gen
          cd RasQberry-pi-gen
          # Customize your Raspberry Pi OS build configuration here
          # For example, edit config or stage files to add/remove software

      - name: Build Raspberry Pi Image
        run: |
          cd RasQberry-pi-gen
          chmod +x ./build.sh
          sudo ./build.sh -c config  # Executes the build process
